# Generated by Django 5.1.3 on 2024-11-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
